services:
  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=12345

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
